### ISSUE TITLE
关于归一化混音函数的问题

### ISSUE THREAD

**Issue by oxidegit** [LightSun/research-institute#1]
您好，我想请问下，归一化混音函数可以对两个pcm音频数据进行混音吗，它的byte[][] allAudioBytes参数是什么意思呢？我这边的pcm数据是一维数组形式。希望您百忙中能抽几分钟帮我解答一下，或者是否方便留下您的联系方式，感激不尽，

**Comment by LightSun** [comment]
可以。978136772
